name: Playwright Tests

on:
  push:
    branches:
      - main  # Trigger the workflow on push to main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull request to main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'  # Specify your desired Node.js version

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install
          npm install -g playwright  # Ensure playwright is installed globally

      # Set up Google TTS and other dependencies (Ensure ffmpeg is installed)
      - name: Install additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          npm install fluent-ffmpeg google-tts-api node-fetch axios
          
      # Run Playwright Tests
      - name: Run Playwright tests
        run: |
          npx playwright install --with-deps  # Install Playwright browser dependencies
          npx playwright test --project=firefox  # Run tests (you can specify a browser)
          
      # Optionally, add steps to save test results or send notifications
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: playwright-test-results
          path: test-results
