name: Trigger Workflow in Another Repo

on:
  push:
    branches:
      - main  

jobs:
  trigger-external:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Repository B Workflows
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_DISPATCH_TOKEN }} # Token created in Step 1
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/surajshindeqa/TestPW/dispatches \
            -d '{"event_type": "triggered-from-repo-A"}'
